(($) ->

  ###*
  # Copyright 2012, Digital Fusion
  # Licensed under the MIT license.
  # http://teamdf.com/jquery-plugins/license/
  #
  # @author Sam Sehnert
  # @desc A small plugin that checks whether elements are within
  #     the user visible viewport of a web browser.
  #     only accounts for vertical position, not horizontal.
  ###

  $.fn.visible = (partial) ->
    $t = $(this)
    $w = $(window)
    viewTop = $w.scrollTop()
    viewBottom = viewTop + $w.height()
    _top = $t.offset().top
    _bottom = _top + $t.height()
    compareTop = if partial == true then _bottom else _top
    compareBottom = if partial == true then _top else _bottom
    compareBottom <= viewBottom and compareTop >= viewTop

  return
) jQuery
win = $(window)
win.load (event) ->
  $('.reveal').each (i, el) ->
    `var el`
    el = $(el)
    if el.visible(true)
      el.addClass 'already-visible'
    return
win.scroll (event) ->
  $('.reveal').each (i, el) ->
    `var el`
    el = $(el)
    if el.visible(true)
      el.addClass 'come-in'
    else
      el.removeClass 'already-visible come-in'
    return
  return

# ---
# generated by js2coffee 2.2.0